name: Continuous Delivery

on: pull_request

jobs:
  static-code-analysis:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: v1.29

  test:
    runs-on: ubuntu-latest
    steps:
    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.13.x

    - name: Checkout code
      uses: actions/checkout@v2

    - name: Test
      run: go test ./...

  build:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Add SHORT_SHA env property with commit short sha
        run:  echo "SHORT_SHA=`echo ${{ github.event.pull_request.head.sha }} | cut -c1-7`" >> $GITHUB_ENV

      - name: Build and Publish head Docker image
        uses: VaultVulp/gp-docker-action@1.1.7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          image-name: my-app
          image-tag: ${{ env.SHORT_SHA }}

      - name: Comment PR
        uses: thollander/actions-comment-pull-request@master
        with:
          message: "successfully build image:  docker.pkg.github.com/${{ github.event.repository.full_name }}/my-app/${{ env.SHORT_SHA }}"
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
